name: Test Matrix

on:
  push:
    branches: [main, '**']
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'ai/**'
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'ai/**'
  workflow_dispatch:

jobs:
  test:
    name: 🧪 Lint, Build & Test ${{ matrix.service }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # Define services with specific Node.js versions or env variables here
        include:
          - service: frontend
            node_version: 20
            env_vars: FRONTEND=true
            sub_packages: ["app", "lib"] # example if you want to parallelize subpackages
          - service: backend
            node_version: 18
            env_vars: BACKEND=true
            sub_packages: ["api", "worker"]
          - service: ai
            node_version: 20
            env_vars: AI=true
            sub_packages: ["core"]

    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request' ||
      github.event_name == 'push' && (
        contains(github.event.head_commit.message, matrix.service) ||
        contains(join(github.event.commits.*.added, ' '), matrix.service) ||
        contains(join(github.event.commits.*.removed, ' '), matrix.service) ||
        contains(join(github.event.commits.*.modified, ' '), matrix.service)
      )

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'none'  # We'll do explicit caching

      - name: Cache node_modules for current service
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: ${{ matrix.service }}/node_modules
          key: ${{ matrix.service }}-node-modules-${{ hashFiles(matrix.service + '/package-lock.json') }}
          restore-keys: |
            ${{ matrix.service }}-node-modules-

      - name: Cache npm cache (optional, speeds up installs)
        uses: actions/cache@v3
        id: cache-npm
        with:
          path: ~/.npm
          key: npm-cache-${{ matrix.node_version }}-${{ hashFiles(matrix.service + '/package-lock.json') }}
          restore-keys: |
            npm-cache-${{ matrix.node_version }}-

      - name: Install dependencies (prefer offline)
        working-directory: ${{ matrix.service }}
        run: npm ci --prefer-offline
        env:
          # Pass service-specific env vars here if needed
          ${{ fromJson(matrix.env_vars) }}

      # If you want to run lint/build/test per sub-package in parallel inside a service job,
      # you can do this using a job-level matrix and a strategy:
      - name: Run Lint, Build, Test in parallel for sub-packages
        run: |
          echo "Running lint/build/test for all sub-packages of ${{ matrix.service }}..."
        # You can replace above with actual parallel execution logic, e.g., with `npm run lint` per sub-package,
        # Or use a composite action or a matrix job for sub-packages.
        # For now, run sequentially for simplicity:

      - name: Lint all sub-packages
        working-directory: ${{ matrix.service }}
        run: |
          for pkg in ${{ join(matrix.sub_packages, ' ') }}; do
            echo "Linting $pkg..."
            npm --prefix $pkg run lint
          done

      - name: Build all sub-packages
        working-directory: ${{ matrix.service }}
        run: |
          for pkg in ${{ join(matrix.sub_packages, ' ') }}; do
            echo "Building $pkg..."
            npm --prefix $pkg run build
          done

      - name: Test all sub-packages
        working-directory: ${{ matrix.service }}
        run: |
          for pkg in ${{ join(matrix.sub_packages, ' ') }}; do
            echo "Testing $pkg..."
            npm --prefix $pkg test
          done

      - name: Upload code coverage artifact
        if: success() && (exists('${{ matrix.service }}/coverage') || exists('${{ matrix.service }}/coverage/lcov.info'))
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.service }}
          path: ${{ matrix.service }}/coverage

      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs-${{ matrix.service }}
          path: |
            ${{ matrix.service }}/test-results
            ${{ matrix.service }}/logs
            ${{ matrix.service }}/coverage
            ${{ matrix.service }}/dist
            ${{ matrix.service }}/build

      - name: Notify Slack on success
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "✅ Lint, build, and tests passed for `${{ matrix.service }}`",
              "attachments": [{ "color": "good" }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "🚨 Lint, build, or tests failed for `${{ matrix.service }}`",
              "attachments": [{ "color": "danger" }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send failure email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "🚨 Lint/build/tests failed for service: ${{ matrix.service }} in repo ${{ github.repository }}"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          body: |
            The lint/build/tests for service "${{ matrix.service }}" failed.
            Check the logs here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Annotate PR on failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const service = "${{ matrix.service }}";
            const message = `Lint/build/tests failed for service **${service}**. Please check the workflow logs.`;
            await github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: `CI - ${service}`,
              head_sha: context.payload.pull_request.head.sha,
              status: 'completed',
              conclusion: 'failure',
              output: {
                title: `CI Failure: ${service}`,
                summary: message
              }
            });
